---

traefik_dashboard_basicauth_file_contents: ''
traefik_config_entrypoint_web_forwardedHeaders_enabled: "{{ traefik_config_entrypoint_web_forwardedHeaders_trustedIPs | length > 0 or traefik_config_entrypoint_web_forwardedHeaders_insecure }}"
traefik_config_entrypoint_web_secure_forwardedHeaders_enabled: "{{ traefik_config_entrypoint_web_secure_forwardedHeaders_trustedIPs | length > 0 or traefik_config_entrypoint_web_secure_forwardedHeaders_insecure }}"
traefik_config_entrypoint_metrics_forwardedHeaders_enabled: "{{ traefik_config_entrypoint_metrics_forwardedHeaders_trustedIPs | length > 0 or traefik_config_entrypoint_metrics_forwardedHeaders_insecure }}"
traefik_config_providers_docker_endpoint_is_unix_socket: "{{ traefik_config_providers_docker_endpoint.startswith('unix://') }}"
