---

- tags:
  - setup-all
  - setup-traefik
  - install-all
  - install-traefik
  block:
  - when: traefik_enabled | bool
    ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

  - when: traefik_enabled | bool
    ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- tags:
  - setup-all
  - setup-traefik
  block:
  - when: not traefik_enabled | bool
    ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
