---
# DNS record type for the Traefik dashboard (A record)
traefik_dns_record_type: "A"

# Record name for the subdomain – this creates traefik.{{ cloudflare_domain }}
traefik_dns_record: "traefik"

# TTL for the DNS record (1 means automatic)
traefik_dns_ttl: 1

# Enable the Cloudflare proxy so that the subdomain is served through the Cloudflare network (orange cloud)
traefik_dns_proxied: true
