---
- name: Install fail2ban (Debian)
  package:
    name: fail2ban
    state: present

- name: Copy jail custom configuration file into place.
  template:
    src: "{{ security_fail2ban_custom_configuration_template }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 644
  notify:
  - reload fail2ban

- name: Copy fail2ban custom configuration file into place for Debian 12 or higher.
  template:
    src: fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: 644
  when: ansible_distribution_major_version | int >= 12
  notify:
  - reload fail2ban

- name: Ensure fail2ban is running and enabled on boot.
  service:
    name: fail2ban
    state: started
    enabled: true
