---
- name: Install OpenSSL
  package:
    name: openssl
    state: latest

- name: Configure DNS record for Traefik Dashboard
  community.general.cloudflare_dns:
    zone: "{{ cloudflare_domain }}"
    api_token: "{{ cloudflare_api_token }}"
    account_email: "{{ cloudflare_account_email }}"
    value: "{{ ansible_host }}"
    record: "traefik"
    type: "A"
    ttl: 1
    proxied: true
  when: cloudflare_setup | bool
  register: dns_result

- name: Configure DNS record for phpMyAdmin Dashboard
  community.general.cloudflare_dns:
    zone: "{{ cloudflare_domain }}"
    api_token: "{{ cloudflare_api_token }}"
    account_email: "{{ cloudflare_account_email }}"
    value: "{{ ansible_host }}"
    record: "phpMyAdmin"
    type: "A"
    ttl: 1
    proxied: true
  when: cloudflare_setup | bool
  register: dns_result

- name: Configure DNS record for the game server
  community.general.cloudflare_dns:
    zone: "{{ cloudflare_domain }}"
    api_token: "{{ cloudflare_api_token }}"
    account_email: "{{ cloudflare_account_email }}"
    value: "{{ ansible_host }}"
    record: "{{ server_subdomain }}"
    type: "A"
    ttl: 1
    proxied: false
  when: cloudflare_setup | bool
  register: dns_result

- name: Display DNS configuration result
  debug:
    var: dns_result
  when: dns_result is defined
