---
- name: Install OpenSSL
  package:
    name: openssl
    state: latest

- name: Configure DNS record for Traefik Dashboard
  community.general.cloudflare_dns:
    zone: "{{ cloudflare_domain }}"
    record: "{{ traefik_dns_record }}"
    type: "{{ traefik_dns_record_type }}"
    value: "{{ ansible_host }}"
    ttl: "{{ traefik_dns_ttl }}"
    proxied: "{{ traefik_dns_proxied }}"
    api_token: "{{ cloudflare_api_token }}"
    account_email: "{{ cloudflare_account_email }}"
  when: cloudflare_setup | bool
  register: dns_result

- name: Display DNS configuration result
  debug:
    var: dns_result
  when: dns_result is defined
