services:
  ansible:
    container_name: ansible
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../ansible:/ansible
      - ~/.ssh:/root/.ssh:ro
    working_dir: /ansible
    environment:
      ANSIBLE_CONFIG: /ansible/ansible.cfg
