services:
  ansible:
    image: cytopia/ansible:2.13
    volumes:
      - ../ansible:/ansible
      - ~/.ssh:/root/.ssh:ro
    working_dir: /ansible
    environment:
      ANSIBLE_CONFIG: /ansible/ansible.cfg
