---
- name: reload systemd
  systemd_service:
    daemon_reload: true

- name: restart ssh
  service:
    name: "{{ security_sshd_name }}"
    state: "{{ security_ssh_restart_handler_state }}"

- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded
