---
- name: Sets up networking with Docker, Traefik and Cloudflare
  hosts: all
  become: true
  gather_facts: true

  vars:
    pip_install_packages:
    - name: docker
    - name: passlib

  roles:
  - pip
  - docker
  - cloudflare
  - proxy
